### ISSUE TITLE
Where did the training data for your model come from?

### ISSUE THREAD

**Issue by zuowanbushiwo** [scofir/DTLN-aec#1]
Hi  
        Have you compared your model with the author's open source tf lite model? The result of comparing your model with real data here is not very good. Is it possible or where did I call it wrong?

Thanks！

**Comment by scofir** [comment]
Aec-challenge

**Comment by scofir** [comment]
Because I only used a small amount of data training, I did not make the data set strictly according to the requirements in the author's paper. The network is built according to the paper.

**Comment by zuowanbushiwo** [comment]
thanks!
